# Generated by Django 5.2.4 on 2025-12-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usertracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertracker',
            old_name='user_id',
            new_name='user',
        ),
    ]
