# Generated by Django 5.2.4 on 2025-12-25 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_story', to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_story', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
