# Generated by Django 5.2.4 on 2025-12-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
