# Generated by Django 5.2.4 on 2025-12-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storypage',
            old_name='content',
            new_name='content_en',
        ),
        migrations.AddField(
            model_name='storypage',
            name='audio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storypage',
            name='audio_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storypage',
            name='content_ko',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
