# Generated by Django 5.2.4 on 2025-12-22 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('story', '0002_alter_story_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='study_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='learning.studyset'),
        ),
    ]
