# Generated by Django 5.2.4 on 2025-12-22 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('unit_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('word', models.CharField(max_length=50)),
                ('meaning', models.CharField(max_length=300)),
                ('cefr_band', models.CharField(max_length=30)),
                ('study_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocas', to='learning.studyset')),
            ],
        ),
    ]
