"""
Django settings for english_academy project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"] # 개발 환경이므로 모든 호스트 허용해야


# Application definition

INSTALLED_APPS = [
    # 'tests', // 지금 당장은 사용하지 않으니 주석 처리
    'story',
    'accounts',
    'community',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 1순위: Vue 프론트엔드와 통신하기 위한 JWT 인증
        'rest_framework_simplejwt.authentication.JWTAuthentication', 
        
        # 2순위: 개발 중 브라우저에서 편리하게 API를 테스트하기 위한 세션 인증
        'rest_framework.authentication.SessionAuthentication',
    ]
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # 보통 30분~60분
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # 보통 1일~7일
    'ROTATE_REFRESH_TOKENS': True,  # 👈 True로 변경: 리프레시 토큰을 쓰면 새 리프레시 토큰도 줌
    'BLACKLIST_AFTER_ROTATION': True, # 👈 True: 사용한 리프레시 토큰은 다신 못 쓰게 함
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,                      # 위쪽의 SECRET_KEY를 사용
    'AUTH_HEADER_TYPES': ('Bearer',),               # Vue에서 'Bearer <token>'으로 보냄
    'BLACKLIST_AFTER_ROTATION': True,               # 토큰 갱신 시 기존 토큰을 블랙리스트에 추가
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 개발 단계에서 모든 도메인 허용
CORS_ALLOW_ALL_ORIGINS = True 

ROOT_URLCONF = 'english_academy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'english_academy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DJANGO_DB_NAME','postgres'),
        'USER': os.environ.get('DJANGO_DB_USER','postgres'),
        'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD','password'),
        'HOST': os.environ.get('DJANGO_DB_HOST','db'),
        'PORT' : '5432',
    }
}

# Docker 및 requirements 설치에 난항을 겪어서 sqlite3으로 임시 적용하려고 코드 사용겸 붙여 놓았습니다.
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'media/'
AUTH_USER_MODEL = 'accounts.User'